sghu/core/urls.py
from django.contrib.auth import views as auth_views
#from .forms import autenticaForm
from django.urls import path
from . import views
from administration.views import ListaRoom
from core.views import CustomLoginView

app_name='core'


    


urlpatterns=[
    path('', views.principal, name='principal'),
    path('signup',views.signup, name='signup'),
   # path('login',auth_views.LoginView.as_view(template_name='login.html',authentication_form=autenticaForm),name='login'),
    path('login', CustomLoginView.as_view(), name='login'),
    path('modificarPerfil',views.modPerfil,name='modificarPerfil'),
    path('articleOne', views.articleOne, name='articleOne'),
    path('articleTwo', views.articleTwo, name='articleTwo'),
    path('articleThree', views.articleThree, name='articleThree'),
    path('articleFour', views.articleFour, name='articleFour'),
    
    path('perfil',views.perfil, name='perfil'),
    path('eliminar_usuario', views.eliminar_usuario, name='eliminar_usuario'),
    path('habitaciones', views.Habitaciones, name='habitaciones'),
    path('troll', views.troll,name='troll')
    
 ]

sghu/sghu/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import custom_logout
from administration.views import users_list,eliminar_usuario,CrearUsuarioView
from factura.views import manageFactura, manageFacturaUpdateView, userFactura,userPagando, ListaFact_toPDF
from perfil.views import CompletarPerfil,ModPerfil


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('reservation.urls')),
    path('', include('administration.urls')),
    path('custom_logout', custom_logout, name='logout'),
    path('users', users_list, name='users_list'),
    path('eliminar_usuario/<str:username>/', eliminar_usuario, name='eliminar_usuario'),
    path('manageFactura',manageFactura.as_view(),name='manageFactura'),
    path('manageFactura/update/<int:pk>/', manageFacturaUpdateView.as_view(), name='manageFactura_update'),
    path('userFactura', userFactura.as_view(), name='userFactura'),
    path('userPagando/<int:pk>/', userPagando.as_view(), name='userPagando'),
    path('CompletarPerfil', CompletarPerfil.as_view(), name='CompletarPerfil'),
    path('ModPerfil', ModPerfil.as_view(), name='ModPerfil'),
    path('ListaFact_toPDF', ListaFact_toPDF.as_view(), name='ListaFact_toPDF'),
    path('CrearUsuarioView/', CrearUsuarioView.as_view(), name='CrearUsuarioView'),



]

sghu/administration/models.py
from django.db import models
from core.models import Hotel
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.
#hotel = Hotel.objects.get(id=1, nombre='Hotel UCI')

class Room(models.Model):
    description = models.CharField(max_length=500)
    price = models.IntegerField(null=False, default=500, validators=[MinValueValidator(500), MaxValueValidator(1300)])
    idHotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    ventilacion = models.CharField(
        verbose_name='Ventilacion',
        max_length=15,
        choices=(
            ('acondicionada', 'Acondicionada'),
            ('ventilador', 'Ventilador')
        ),
        default='1'
    )
    temperaturaAgua = models.CharField(
        verbose_name='TemperaturaAgua',
        max_length=10,
        choices=(
            ('fria', 'Fría'),
            ('caliente', 'Caliente')
        ),
        default='1'
    )
    television=models.BooleanField(default=False)
    disponible=models.BooleanField(default=True)
    def __str__(self):
        return self.description

sghu/core/models.py
from django.db import models

# Create your models here.




class Hotel(models.Model):
    nombre = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'Hotels'
              
    def __str__(self):
        return self.nombre
    

sghu/perfil/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
# Create your models here.


class Perfil(models.Model):
    ci = models.CharField(max_length=11, validators=[RegexValidator(regex='^[0-9]{11}$', message='El CI debe tener 11 dígitos')],blank=False)
    phone = models.CharField(max_length=8, validators=[RegexValidator(regex='^5[0-9]{7}$', message='El número de teléfono debe comenzar con 5 y tener 8 dígitos')],blank=False)
    adress=models.CharField(max_length=30)
    bio=models.TextField(max_length=500)
    usuarioRelacionado=models.OneToOneField(User,on_delete=models.CASCADE)

sghu/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

class SignupForm(UserCreationForm):
    class Meta:
        model=User
        fields=('username','email','password1','password2')
    username=forms.CharField(required=True,widget=forms.TextInput(attrs={
        'placeholder':'Nombre de usuario', 
        'class': 'form-control py-2 px-6 rounded-lg' 
        }))
    email=forms.CharField(required=True, widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'form-control py-2 px-6 rounded-lg'
        }))
    password1=forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'placeholder': 'Tu contraseña',
        'class': 'form-control py-2 px-6 rounded-lg'
        }))
    password2=forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirma tu contraseña',
        'class': 'form-control py-2 px-6 rounded-lg'
        }))
    
    
class autenticaForm(AuthenticationForm):
    username=forms.CharField(required=True,widget=forms.TextInput(attrs={
        'placeholder':'Nombre de usuario', 
        'class': 'form-control py-2 px-6 rounded-lg' 
        }))
    password=forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'placeholder': 'Tu contraseña',
        'class': 'form-control py-2 px-6 rounded-lg'
        }))

sghu/perfil/forms.py
from django.forms import ModelForm
from django.forms import *
from django import forms
import pytz
from django.utils.html import format_html
from datetime import date, timedelta
from .models import Perfil
from datetime import datetime


class NameWidget(widgets.Widget):
    def render(self, name, value, attrs=None, renderer=None):
        return value

class PerfilForms(forms.ModelForm):
    ci = forms.CharField(label='Carnet de identidad (Necesario):')
    phone = forms.IntegerField(label='Teléfono (Necesario):')
    adress = forms.CharField(label='Dirección:')
    bio = forms.CharField(label='Biografía:', widget=forms.Textarea)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['adress'].required = False
        self.fields['bio'].required = False
    
    
    
    
    class Meta:
        model = Perfil
        fields = ['ci', 'phone', 'adress', 'bio']
        widgets = {
            'ci': forms.TextInput(attrs={'class': 'hide-field','class': 'form-control py-2 px-6 rounded-lg',
             'placeholder':'Ejemplo: 12121289121' ,'type': 'number','id':'id_ci'                      }),
            
            'phone': forms.TextInput(attrs={'class': 'form-control py-2 px-6 rounded-lg',
                                 'placeholder': 'Ejemplo: 51111111', 'type': 'number', 'id': 'id_ph',
                                  'pattern': '[0-9]{8}', 'maxlength': '8'}),
            
            'adress': forms.TextInput(attrs={'maxlength': 30,'class': 'form-control py-2 px-6 rounded-lg',
              'placeholder':'Ejemplo: Calle 30 E/ ave 20 y 25 #8509 Boyeros La Habana'                                }),
            
            'bio': forms.Textarea(attrs={'maxlength': 500,'class': 'form-control py-2 px-6 rounded-lg',
             'placeholder':'Un poco de información sobre usted'                            }),
        }
        
    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if not (50000000 <= int(phone) <= 59999999):
            raise forms.ValidationError('El número de teléfono debe comenzar con 5 y tener 8 dígitos')
        return phone
        
    def clean_ci(self):
        ci = self.cleaned_data['ci']
        if not (len(ci) == 11 and ci.isdigit()):
            raise forms.ValidationError('El CI debe tener 11 dígitos')
        
         # Obtener el año actual menos 18
        ano_maximo = datetime.now().year - 18
    
     # Obtener el año de nacimiento a partir de los dos primeros dígitos del número de identificación
        ano = int(ci[:2])
        if ano <= int(str(ano_maximo)[2:]):
         ano += 2000
        else:
          ano += 1900

    # Verificar que el año de nacimiento está entre 1944 y el año actual menos 18
        if ano < 1944 or ano > ano_maximo:
            raise forms.ValidationError('No cumple con la edad necesaria')
    
    # Obtener el mes y el día de nacimiento a partir de los siguientes cuatro dígitos del número de identificación
        mes = int(ci[2:4])
        dia = int(ci[4:6])
    
    # Verificar que el mes y el día de nacimiento son válidos
        try:
          datetime(ano, mes, dia)
        except ValueError:
          raise forms.ValidationError('El mes y/o día de nacimiento no son válidos')
    
        
        return ci
        

sghu/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SignupForm
from django.contrib.auth import authenticate,login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
import datetime
from django.contrib.auth.models import User
from administration.models import Room
from reservation.models import Reservacion
from factura.models import Factura
from perfil.models import Perfil
from django.contrib.auth.decorators import user_passes_test
from .forms import autenticaForm
# Create your views here.

def user_is_not_authenticated(user):
    return not user.is_authenticated


def principal(request):
    updateDisponibilidad()
    #usuario_pertenece_a_grupo = request.user.groups.filter(name='Clientes').exists()
    #context = {'usuario_pertenece_a_grupo': usuario_pertenece_a_grupo}
    return render(request, 'principal.html')
def articleOne(request):
    return render(request,'1article.html')

def articleTwo(request):
    return render(request,'2article.html')

def articleThree(request):
    return render(request,'3article.html')

def articleFour(request):
    return render(request,'4article.html')

class CustomLoginView(LoginView):
    template_name = 'login.html'
    authentication_form = autenticaForm

    def form_valid(self, form):
        # Llamamos a la implementación de form_valid de LoginView
        response = super().form_valid(form)

        # Verificamos si el usuario tiene los campos ci y phone en su perfil
        perfil = self.request.user.perfil
        if not perfil.ci or not perfil.phone:
            # Si los campos están nulos, redirigimos al usuario a completar su perfil
            return redirect('CompletarPerfil')
        
        # Si los campos no están nulos, redirigimos al usuario a su dashboard
        return redirect('core:principal')
    
    
    
    
    
    
@user_passes_test(user_is_not_authenticated)
def signup(request):
    data={'form':SignupForm()}

    if request.method == 'POST':
        form= SignupForm(data=request.POST)

        if form.is_valid():
            
            form.save()
            perfil = Perfil.objects.create(
                usuarioRelacionado=User.objects.get(username=request.POST['username'])
            )
                        
            

            username2 = request.POST['username']
            password2 = request.POST['password1']
            user = authenticate(request, username=username2, password=password2)
            
            if user is not None:
                login(request, user)
                return redirect('CompletarPerfil')
            else:
                # Handle invalid login credentials
             pass
       
    else:
    
        form=SignupForm()

    return render(request, 'signup.html',{
        'form':form
    })

def custom_logout(request):
        logout(request)
        return redirect('../')
    
@login_required
def perfil(request):
    context = {}
    try:
        context['perfil'] = Perfil.objects.get(usuarioRelacionado=request.user)
    except Perfil.DoesNotExist:
        pass
    return render(request, 'perfil.html', context)
@login_required
def modPerfil(request):
    usuario = request.user
    if request.method == 'POST':
        usuario.username = request.POST['usermod']
        usuario.email = request.POST['emailmod']
        usuario.first_name = request.POST['nombremod']
        usuario.last_name=request.POST['apellmod']
        usuario.save()
        return redirect('core:perfil')
    else:

      return render(request, 'modificarPerfil.html', {'usuario': usuario})



@login_required
def eliminar_usuario(request):
    if request.method=='POST':
         nombreU=request.user.username
         
         logout(request)
         objeto = get_object_or_404(User, username=nombreU)
         objeto.delete()
         return redirect('core:principal')
        
    else:
        return render(request, 'eliminar_usuario.html')
@login_required
def Habitaciones(request):
    updateDisponibilidad()
    
    rooms = Room.objects.all()
    image_names = ['1.jpg', '2.jpg', '3.jpg','4.jpg']
    context = {'rooms': rooms,'image_names':image_names}
    if request.user.is_authenticated:
     perfil = request.user.perfil
     if not perfil.ci or not perfil.phone:
            # Si los campos están nulos, redirigimos al usuario a completar su perfil
            return redirect('CompletarPerfil')
    return render(request, 'habitaciones.html', context)


def updateDisponibilidad():
     
     rooms=Room.objects.all()
     reservas=Reservacion.objects.all()
     facturas=Factura.objects.all()
     
     
     
     for e in reservas:
         fechafinmajuno =e.fechaDeFin + datetime.timedelta(days=1)
         fechaIniciomenojdo=e.fechaDeInicio - datetime.timedelta(days=2)
         if(fechaIniciomenojdo <= datetime.date.today()):
             for f in facturas:
                 
               if f.idReservacion == e:    
                 e.delete()
             return None
         if(fechafinmajuno <= datetime.date.today()):
             habitacion=rooms.get(id=e.idRoom.id)
             habitacion.disponible=True
             habitacion.save()
             e.delete()
             return None
         if(e.fechaDeInicio>=datetime.date.today() and e.fechaDeFin>datetime.date.today()):
             habitacion=rooms.get(id=e.idRoom.id)
             habitacion.disponible=False
             habitacion.save()
     
     return None
def troll(request):
    return render(request,'403_troll.html')

sghu/perfil/views.py
from typing import Any, Dict, Optional
from django.db import models
from django.shortcuts import render, redirect
from django.views.generic import DeleteView, ListView, CreateView, UpdateView
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PerfilForms
from .models import Perfil

# Create your views here.



    
   
    
class CompletarPerfil(LoginRequiredMixin,UpdateView):
    model = Perfil
    template_name = 'completarPerfil.html'
    form_class = PerfilForms
    success_url = reverse_lazy('listarReservaciones')

    def get_object(self, queryset=None):
        # Obtener el objeto Perfil asociado al usuario actual
        return self.request.user.perfil

    def form_valid(self, form):
        # Asociar el objeto Perfil actual con el usuario actual
        perfil = form.save(commit=False)
        perfil.save()
        return super().form_valid(form)
    
class ModPerfil(LoginRequiredMixin,UpdateView):
    model = Perfil
    template_name = 'modP.html'
    form_class = PerfilForms
    success_url = reverse_lazy('core:perfil')

    def get_object(self, queryset=None):
        # Obtener el objeto Perfil asociado al usuario actual
        return self.request.user.perfil

    def form_valid(self, form):
        # Asociar el objeto Perfil actual con el usuario actual
        perfil = form.save(commit=False)
        perfil.save()
        return super().form_valid(form)
    

class ListaPerfil(LoginRequiredMixin,ListView):
    model = Perfil
    template_name = 'gestionarReservacion.html'
    queryset = Perfil.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        return context

sghu/core/templates/403_troll.html
{%extends 'base.html'%}
{% load static %}
{%block title%} Sign up {% endblock %}



{% block content %}
<br>
<style>
    body{
        background-image: url("{% static 'medias/troll.jpg'%}");
        background-size: cover;
    
    }
    </style>
    <br>
<div class="container mi-div p-5 ">
    <div class="d-flex justify-content-center align-items-center vh-100">
        <div class=" w-70 bg-white p-5 rounded-3 border border-secondary">
            <h1 class="d-flex justify-content-center mb-6 text-3xl">No me digas</h1>




                <br>
                <br>
                
        
        </div>
    </div>
</div>



    




{% endblock %}

sghu/core/templates/base.html
{% load static %}
{% load my_tags %}
<!DOCTYPE html>
<html lang="es">
<head>
    <title>{% block title %}{% endblock %} | SGHU</title>
    <meta charset="iso-8859-1">
    <meta name="author" content="Arizael/Elena/Daynelis">
    <meta name="description" content="PW project">
    <link rel="stylesheet" href="{% static 'css\estiloFooter.css' %}">
    <link rel="stylesheet" href="{% static 'css\bootstrap-datepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'css\bootstrap-5.1.3-dist\css\bootstrap.min.css'%}">

    <script src="{% static 'js\bootstrap.js'%}"></script>
    <script src="{% static 'js\bootstrap.min.js'%}"></script>
    
    <link href="http://code.jquery.com/ui/1.9.2/themes/smoothness/jquery-ui.css" rel="stylesheet" />
    <script src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
    <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>

    <script src="{% static 'js\jquery-3.6.4.min.js'%}"></script>
    <script src="{% static 'js\jquery-ui-1.13.2\jquery-ui.min.js'%}"></script>
    <script src="{% static 'js\jquery-ui-1.13.2\jquery-ui.js'%}"></script>

    
    <script src="{% static 'js\animate.js'%}"></script>
    <link rel="icon" href="{% static 'medias/Logo SGAHU.jpg'%}" type="image/x-icon">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</head>

<body>
<style>


    nav {
        background-color: #1c75bc;
        color: #fff; /* Color de texto blanco para contrastar con el fondo azul */
        padding: 10px; /* Agregar un poco de espacio entre el contenido y el borde del nav */
    }
    .back-link {
        position: fixed;
        bottom: 20px;
        left: 20px;
        background-color: #333;
        color: #fff;
        padding: 10px 20px;
        border-radius: 5px;
        text-decoration: none;
        font-size: 14px;
      }
      
      .back-link:hover {
        background-color: #444;
      }

</style>
{% comment %} <a href="javascript:history.back()" class="back-link">Volver</a> {% endcomment %}
<header id="" class="">
    <nav class="navbar navbar-expand-sm navbar-dark " id="naveg" >
        <div class="container-fluid">
            <a href="../"class="navbar-brand"> <img src="{% static 'medias/Logo SGAHU Listo.png'%}" class="img-fluid" width="52" height="46">&nbspSistema de Gesti&oacute;n del Hotel UCI</a>
            <!-- Elementos del navbar -->
            <a class="navbar-brand text-white" href="#"></a>


            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link text-white" aria-current="page" href="{% url 'core:principal' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'listarReservaciones' %}">Reservaciones</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" diabled href="{% url 'core:habitaciones' %}">Habitaciones</a>
                </li>
                <!-- AQUI VA LA CONDICIIONAL PARA RECEPCIONISTA Y ADMIN-->
                {% if request.user.is_authenticated and not request.user|is_in_group:"Clientes" %}
                      <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{% static 'medias/diente.png'%}" alt="" style="width: 30px;">
                        </button>
                        <ul class="dropdown-menu">
                            {%if request.user.is_superuser%}
                               <li><a class="dropdown-item" href="{% url 'manageReservation' %}">Administrar Reservaciones</a></li>
                               <li><a class="dropdown-item" href="{% url 'users_list' %}">Administrar Usuarios</a></li>
                               <li><a class="dropdown-item" href="{% url 'listarRoom' %}">Administrar Habitaciones</a></li>
                               <li><a class="dropdown-item" href="{% url 'manageFactura' %}">Visualizar Facturas</a></li>
                               <li><a class="dropdown-item" href="{% url 'CrearUsuarioView' %}">Crear Usuario</a></li>
                            {%else%}
                               <li><a class="dropdown-item" href="{% url 'manageReservation' %}">Administrar Reservaciones</a></li>
                               <li><a class="dropdown-item" href="{% url 'listarRoom' %}">Administrar Habitaciones</a></li>
                               <li><a class="dropdown-item" href="{% url 'manageFactura' %}">Visualizar Facturas</a></li>
                               {%endif%}          
                        </ul>
                      </div>

                {% endif %}
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'core:perfil' %}">Perfil:&nbsp{{request.user.username}}</a>
              </li>
               <li class="nav-item">
                 <!-- cerrar sesión -->
                    <a class="nav-link text-white" diabled href="{% url 'logout' %}">
                     <img src="{% static 'medias/log-out.png'%}" alt="" style="width: 30px;">
                    </a>
               </li>
           {% else %}
           <li class="nav-item">
             <a class="nav-link text-white" diabled href="{% url 'core:signup' %}">Registrarse</a>
         </li>
           <li class="nav-item">
             <!-- iniciar sesión -->
               <a class="nav-link text-white" href="{% url 'core:login' %}">
                 <img src="{% static 'medias/login.png'%}" alt="" style="width: 30px;">
               </a>
           </li>
           
                {% endif %}
                
               
            </ul>
        </div>
    </nav>


</header>

{%block content%}

{%endblock%}


<br>
<br>
<br>


<footer class="d-flex flex-wrap justify-content-between align-items-center border-top">
      <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><img src="{% static 'medias/Logo SGAHU Listo.png'%}" alt=""width="50"></svg>
        </a class="">
        <span class="mb-3 mb-md-0 text-white">&copy; 2022 Company, Inc</span>
      </div>
  
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <a class="btn"><img src="{% static 'medias/Twitter.png'%}" alt=""width="50"></a>
        <a class="btn"><img src="{% static 'medias/telegram.png'%}" alt=""width="50"></a>
        <a class="btn"><img src="{% static 'medias/Linkedin.png'%}" alt=""width="50"></a>
        <a class="btn"><img src="{% static 'medias/github.png'%}" alt=""width="50"></a>
      </ul>
</footer>

</body>
</html>

sghu/core/templates/eliminar_usuario.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-center align-items-center bg-secondary h-100 w-100">
  <div class="text-center text-white">
    <h1>Eliminar cuenta de usuario</h1>
    <p>Se eliminará su usuario</p>
    <form method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Aceptar</button>
    </form>
  </div>
</div>
{% endblock %}

sghu/core/templates/habitaciones.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Welcome {% endblock %}

{% block content %}

<div class="container">
    <h1>Habitaciones disponibles</h1>
    <hr>
    {% for room in rooms %}
    
      <div class="row">
        <div class="col-md-4">
            {%if room.price < 600 %}
                <img src="{% static 'medias/Habitaciones/1.jpg' %}" class="img-fluid">
                     {% elif room.price < 800 and room.price >= 600 %}
                        <img src="{% static 'medias/Habitaciones/2.jpg' %}" class="img-fluid">
                           {% elif room.price < 900 and room.price >= 800 %}
                               <img src="{% static 'medias/Habitaciones/3.jpg' %}" class="img-fluid">
                                     {% elif room.price <= 1000 and room.price >= 900 %}
                                        <img src="{% static 'medias/Habitaciones/4.jpg' %}" class="img-fluid">
            {%endif%}
        </div>
        <div class="col-md-8">
          <h2>{{ room.description }}</h2>
          <p>Precio: {{ room.price }} CUP</p>
          <p>Ventilación: {{ room.get_ventilacion_display }}</p>
          <p>Temperatura del agua: {{ room.get_temperaturaAgua_display }}</p>
          <p>Televisión: {% if room.television %}Sí{% else %}No{% endif %}</p>
          <a href="{% url 'crearReservaciones' room.id  %}" class="btn btn-primary"><i class='bx bxs-spreadsheet'></i>Reservar</a>
          <!--room.id-->
        </div>
      </div>
      <hr>
    {% endfor %}
  </div>
  <br>
  <br>
  <br>
  <br>

{% endblock %}

sghu/core/templates/login.html
{%extends 'base.html'%}
{% load static %}
{%block title%} Iniciar Sesión {% endblock %}



{% block content %}
<br>
<style>
    body{
        background-image: url("{% static 'medias/hotel fachada.jpg'%}");
        background-size: cover;
    
    }

    .error-message {
			color: red;
		}
    
    .error-box {
        background-color: white;
        border: 2px solid red;
        border-radius: 5px;
        padding: 10px;
        margin-bottom: 10px;
    }
</style>
{% if user.is_authenticated %}
    <h1 class="text-center ">Ya ha iniciado sesión</h1>
{% else %}
    <div class="container p1 ">
        <div class="d-flex justify-content-center align-items-center vh-100">
            <div class=" w-70 p-5 rounded-3 border border-secondary" style="background: transparent; border: 2px solid rgba(255, 255, 255, 0.5); border-radius: 20px; backdrop-filter: blur(15px);">
                <h1 class="d-flex justify-content-center text-white mb-6 text-3xl">Bienvenido</h1>

                <form method="post" action="">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label class="form-label d-flex justify-content-center text-white fw-bold">Nombre de usuario</label>
                        {{ form.username}}
                    </div>

                    <div class="mb-3">
                        <label class="form-label d-flex justify-content-center text-white fw-bold">Contraseña</label>
                        {{ form.password}}
                    </div>

                    {% if form.errors or form.non_field_errors %}
                        <div class="error-box">
                            <div class="error-message">
                                {% for field in form %}
                                    {{ field.errors }}
                                {% endfor %}
                                {{ form.non_field_errors }}
                            </div>
                        </div>
                    {% endif %}

                    <label class="text-white">¿No tiene una cuenta? <a href="{% url 'core:signup' %}" style="color: rgb(126, 145, 255);">Registrarse</a></label>

                    <br>
                    <br>
                    <div class="justify-content-center align-items-center d-flex">
                        <button type="submit"  class="btn btn-primary mx-2">
                          <a class="text-white text-decoration-none no-underline" onclick="window.location.href=''" >Iniciar sesión</a>
                        </button>
                    
                        <button type="button"   class="btn btn-secondary  float-md-end ">
                          <a class="text-white text-decoration-none" onclick="window.history.back()">Cancelar</a>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}