sghu/administration/urls.py
from django.urls import path
from .views import ListaRoom,CrearRoom,EliminarRoom,ModRoom,manageReservations,editarUsuario


urlpatterns = [
path('adminRoom',ListaRoom.as_view(), name='listarRoom'),
path('anadirRoom',CrearRoom.as_view(), name='anadirRoom'),
path('eliminarRoom/<int:pk>/', EliminarRoom.as_view(), name='eliminarRoom'),
path('modRoom/<int:pk>/', ModRoom.as_view(), name='modRoom'),
path('manageReservation/', manageReservations, name='manageReservation'),
path('editarUsuario/<int:user_id>/', editarUsuario.as_view(), name='editarUsuario'),

]

sghu/core/urls.py
from django.contrib.auth import views as auth_views
#from .forms import autenticaForm
from django.urls import path
from . import views
from administration.views import ListaRoom
from core.views import CustomLoginView

app_name='core'


    


urlpatterns=[
    path('', views.principal, name='principal'),
    path('signup',views.signup, name='signup'),
   # path('login',auth_views.LoginView.as_view(template_name='login.html',authentication_form=autenticaForm),name='login'),
    path('login', CustomLoginView.as_view(), name='login'),
    path('modificarPerfil',views.modPerfil,name='modificarPerfil'),
    path('articleOne', views.articleOne, name='articleOne'),
    path('articleTwo', views.articleTwo, name='articleTwo'),
    path('articleThree', views.articleThree, name='articleThree'),
    path('articleFour', views.articleFour, name='articleFour'),
    
    path('perfil',views.perfil, name='perfil'),
    path('eliminar_usuario', views.eliminar_usuario, name='eliminar_usuario'),
    path('habitaciones', views.Habitaciones, name='habitaciones'),
    path('troll', views.troll,name='troll')
    
 ]

sghu/sghu/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import custom_logout
from administration.views import users_list,eliminar_usuario,CrearUsuarioView
from factura.views import manageFactura, manageFacturaUpdateView, userFactura,userPagando, ListaFact_toPDF
from perfil.views import CompletarPerfil,ModPerfil


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('reservation.urls')),
    path('', include('administration.urls')),
    path('custom_logout', custom_logout, name='logout'),
    path('users', users_list, name='users_list'),
    path('eliminar_usuario/<str:username>/', eliminar_usuario, name='eliminar_usuario'),
    path('manageFactura',manageFactura.as_view(),name='manageFactura'),
    path('manageFactura/update/<int:pk>/', manageFacturaUpdateView.as_view(), name='manageFactura_update'),
    path('userFactura', userFactura.as_view(), name='userFactura'),
    path('userPagando/<int:pk>/', userPagando.as_view(), name='userPagando'),
    path('CompletarPerfil', CompletarPerfil.as_view(), name='CompletarPerfil'),
    path('ModPerfil', ModPerfil.as_view(), name='ModPerfil'),
    path('ListaFact_toPDF', ListaFact_toPDF.as_view(), name='ListaFact_toPDF'),
    path('CrearUsuarioView/', CrearUsuarioView.as_view(), name='CrearUsuarioView'),



]

sghu/administration/models.py
from django.db import models
from core.models import Hotel
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.
#hotel = Hotel.objects.get(id=1, nombre='Hotel UCI')

class Room(models.Model):
    description = models.CharField(max_length=500)
    price = models.IntegerField(null=False, default=500, validators=[MinValueValidator(500), MaxValueValidator(1300)])
    idHotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    ventilacion = models.CharField(
        verbose_name='Ventilacion',
        max_length=15,
        choices=(
            ('acondicionada', 'Acondicionada'),
            ('ventilador', 'Ventilador')
        ),
        default='1'
    )
    temperaturaAgua = models.CharField(
        verbose_name='TemperaturaAgua',
        max_length=10,
        choices=(
            ('fria', 'Fría'),
            ('caliente', 'Caliente')
        ),
        default='1'
    )
    television=models.BooleanField(default=False)
    disponible=models.BooleanField(default=True)
    def __str__(self):
        return self.description

sghu/factura/models.py
from django.db import models
from django.contrib.auth.models import User
from administration.models import Room
from reservation.models import Reservacion
# Create your models here.

class Factura(models.Model):
	metodoDePago=models.CharField(max_length=11)
	fechaDeInicio=models.DateField()
	fechaDeFin=models.DateField()
	monto=models.FloatField()
	idUsuario=models.ForeignKey(User,on_delete=models.CASCADE)
	idRoom=models.ForeignKey(Room,on_delete=models.CASCADE)
	idReservacion=models.ForeignKey(Reservacion, on_delete=models.CASCADE)
	pagada=models.BooleanField(default=False)
	


	def __str__(self):
		return self.ID

sghu/administration/forms.py
from django.forms import ModelForm
from django.forms import *
from django import forms
from .models import Room
from django.utils.html import format_html



class RoomForm(ModelForm):
   
    def __init__(self, *args, **kwargs):
       # name_initial = kwargs.pop('name_initial', None)
        super().__init__(*args, **kwargs)
        self.fields['idHotel'].initial = 1
        
    class Meta:
        model = Room
        fields = ['description','price','ventilacion','temperaturaAgua','television','idHotel']
        
        widgets = {
            'description': forms.TextInput(attrs={}),
            
        }
        

sghu/administration/views.py
from django.contrib.auth.models import User
from core.models import Hotel
from .models import Room
from reservation.models import Reservacion
from administration.forms import RoomForm
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import DeleteView, ListView, CreateView, UpdateView, View
from .UserForm import UserForm, CrearUsuarioForm
from django.contrib.auth.forms import UserCreationForm
from perfil.models import Perfil
from django.contrib.auth.models import Group

class CrearUsuarioView(LoginRequiredMixin,UserPassesTestMixin,View):
    def get(self, request):
        form = CrearUsuarioForm()
        context = {'form': form}
        return render(request, 'crear_usuario.html', context)
    def test_func(self):
        return self.request.user.is_staff

    def post(self, request):
        form = CrearUsuarioForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_staff = form.cleaned_data['is_staff']
            user.save()
            perfil = Perfil.objects.create(
                usuarioRelacionado=User.objects.get(username=request.POST['username'])
            )
            return redirect('users_list')
        context = {'form': form}
        return render(request, 'crear_usuario.html', context)



@login_required
def users_list(request):
    # Obtener la lista de usuarios del sistema
    users = User.objects.all()

    # Pasar la lista de usuarios al template
    context = {'users': users}
    return render(request, 'users_list.html', context)

@login_required
def manageReservations(request):
        reservations=Reservacion.objects.all()
        rooms=Room.objects.all()
        context={'reservations':reservations,'rooms':rooms}
        perfil = request.user.perfil
        if not perfil.ci or not perfil.phone:
            # Si los campos están nulos, redirigimos al usuario a completar su perfil
            return redirect('CompletarPerfil')
        return render(request, 'manageReservation.html', context)

@login_required
def eliminar_usuario(request, username):
    user = User.objects.get(username=username)
    user.delete()
    return redirect('users_list')

#Vistas basadas en clase de las habitaciones
class CrearRoom(LoginRequiredMixin,CreateView):
    model = Room
    template_name = 'anadirRoom.html'
    form_class = RoomForm
    queryset = Room.objects.all()
    success_url = reverse_lazy('listarRoom')
    
    def dispatch(self, request, *args, **kwargs):
        perfil = self.request.user.perfil
        if not perfil.ci or not perfil.phone:
            return redirect('CompletarPerfil')
        return super().dispatch(request, *args, **kwargs)
    def get_initial(self):
        initial = super().get_initial()
        initial['idHotel'] = 1
        return initial
    def form_valid(self, form):
        # Comprobamos si existe alguna habitación con la descripción proporcionada
        if Room.objects.filter(description=form.cleaned_data['description']).exists():
            form.add_error('description', 'Ya existe una habitación con esta descripción.')
            return super().form_invalid(form)
    
        
        return super().form_valid(form)
    def get_queryset(self):
        return Room.objects.all() 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # NOOOOO Condicionales para habitaciones para crear
    #     if self.queryset.count() >= 20:
    #         context['todasHabitaciones'] = True
    #     else:
    #    #     context['todasHabitaciones'] = False
      #  context['habitaciones']=20-self.queryset.count()
        
        return context


class ListaRoom(LoginRequiredMixin,ListView):
    model = Room
    template_name = 'manageroom.html'
    queryset = Room.objects.all().order_by('-price')
    
    def dispatch(self, request, *args, **kwargs):
        perfil = self.request.user.perfil
        if not perfil.ci or not perfil.phone:
            return redirect('CompletarPerfil')
        return super().dispatch(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #Condicionales para habitaciones para crear
        if self.queryset.count() >= 20:
            context['todasHabitaciones'] = True
        else:
            context['todasHabitaciones'] = False
        disponibles=20-self.queryset.count()
        context['habitaciones']=20-self.queryset.count()
        
        return context

class EliminarRoom(LoginRequiredMixin,DeleteView):
    model = Room
    template_name = 'eliminarRoom.html'
    success_url = reverse_lazy('listarRoom')
    
    def dispatch(self, request, *args, **kwargs):
        perfil = self.request.user.perfil
        if not perfil.ci or not perfil.phone:
            return redirect('CompletarPerfil')
        return super().dispatch(request, *args, **kwargs)
    

class ModRoom(LoginRequiredMixin,UpdateView):
    model = Room
    template_name = 'modRoom.html'
    form_class = RoomForm
    success_url = reverse_lazy('listarRoom')
    
    def dispatch(self, request, *args, **kwargs):
        perfil = self.request.user.perfil
        if not perfil.ci or not perfil.phone:
            return redirect('CompletarPerfil')
        return super().dispatch(request, *args, **kwargs)
    
class editarUsuario(LoginRequiredMixin,View):
    def get(self, request, user_id):
        user = get_object_or_404(User, pk=user_id)
        form = UserForm(instance=user)
        context = {'form': form, 'user': user}
        return render(request, 'editUser.html', context)

    def post(self, request, user_id):
        user = get_object_or_404(User, pk=user_id)
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            user.first_name = request.POST.get('first_name')
            user.last_name = request.POST.get('last_name')
            user.email = request.POST.get('email')
            user.is_active = request.POST.get('is_active') == 'on'
            user.is_staff = request.POST.get('is_staff') == 'on'
            user.is_superuser = request.POST.get('is_superuser') == 'on'
            user_permissions = form.cleaned_data['user_permissions']
            user.user_permissions.set(user_permissions)
        if not user.is_staff and not user.is_superuser:
            grupo_clientes = Group.objects.get(name='Clientes')
            if grupo_clientes not in user.groups.all():
                user.groups.add(grupo_clientes)
        else:
            grupo_clientes = Group.objects.get(name='Clientes')
            if grupo_clientes in user.groups.all():
                user.groups.remove(grupo_clientes)
        user.save()
        print(request.POST) 
        user.save() 
        return redirect('users_list')

sghu/administration/templates/anadirRoom.html
{%extends 'base.html'%}
{% load static %}
{% load crispy_forms_tags %}
{%block title%} New Room {% endblock %}


{% block content %}

    <div class="bg-white">
        <br>
        <br>
        {% block titulo %}
            <h3 class="card-title text-center fw-bold">Añadir Habitación</h3>
        {% endblock %}
        <style>
        .hide-field {
            display: none;
                }
      </style>
        <div class=" container w-50">

            <form class="for form-control form-row" method="post">

                <div class="card-body">
                    {% csrf_token %}
                    {% block forms %}
                        {{ form| crispy }}
                    {% endblock %}


                </div>
                <div class=" justify-content-center">
                    
                    <button type="submit" class="btn btn-primary">Confirmar</button>
                    <a href="{% url 'listarRoom' %}" class="btn btn-danger float-right">Cancelar</a>

                </div>
            </form>


        </div>
        <br>
        <br>
        <br>
    </div>

{% endblock %}

sghu/administration/templates/crear_usuario.html
{% extends 'base.html' %}
{% load static %}
{%block title%} Crear Usuario {% endblock %}
{% block content %}
<style>
  body{
      background-image: url("{% static 'medias/esteSi.jpg'%}");
      background-size: 100% 100%;
  
  }
  </style>
<br>
<br>

  <div class="for form-control form-row w-50" action="" style=" margin-left: 350px; display: flex; flex-direction: column;
  align-items: center;" style="width: 600px; padding: 30px;">
{% if request.user.is_staff %}
  <h1>Crear usuario:</h1>
  
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary" style="margin-left: 100px;">Guardar cambios</button>
    <a href="{% url 'users_list' %}" class="btn btn-secondary" style="margin-left: 100px;">Cancelar</a>
  </form>
  {% else %}
  <h1 class="text-center ">Acceso Denegado</h1>
  {%endif%}
  </div>
{% endblock %}

sghu/administration/templates/editUser.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if request.user.is_superuser %}
<style>
  body{
      background-image: url("{% static 'medias/esteSi.jpg'%}");
      background-size: 100% 100%;
  
  }
  .user-permissions-field {
        max-height: 100px;
        overflow-y: auto;
        border: 1px solid #ccc;
        padding: 5px;
      }
  </style>
<br>
<br>

  <div class="for form-control form-row w-50" action="" style=" margin-left: 350px; display: flex; flex-direction: column;
  align-items: center;" style="width: 600px; padding: 30px;">
    {% if request.user.is_staff %}
    <h1 class="text-center">Editar usuario: {{ user.username }}</h1>
    <form method="post">
      {% csrf_token %}
    <label >Nombre de usuario</label>
    {{ form.username }}
    <label >Email</label>
    {{ form.email }}
    <label >Nombre:</label>
    {{ form.first_name }}
    <label >Apellidos:</label>
    {{ form.last_name }}
    <label >Activo: </label>
    {{ form.is_active }}
    <label >Es staff: </label>
    {{ form.is_staff }}
    <label >Es Super User: </label>
    {{ form.is_superuser }}
    <!-- <div class="form-group">
      <label for="{{ form.user_permissions.id_for_label }}">Permisos de usuario</label>
      <div class="user-permissions-field">
        {{ form.user_permissions }}
      </div>
    </div> -->
    <br>
    <div style="margin-left: 400px;">
      <button class="btn btn-primary" type="submit">Guardar</button>
    </div>
    
    </form>
    {% else %}
    <h1 class="text-center ">Acceso Denegado</h1>
    {% endif %}
  </div>
  
  {%else%}
  <h1 class="text-center ">Acceso Denegado</h1>
 {% endif %}


{% endblock %}

sghu/administration/templates/eliminarRoom.html
{%extends 'base.html'%}
{% load static %}
{% load crispy_forms_tags %}
{%block title%} Eliminar Room {% endblock %}


{% block content %}
    <br>
    <div class="d-flex justify-content-center">
  <div>
    <div class="card-header bg-primary text-white">
      <h3 class="card-title text-center">Eliminar Room</h3>
    </div>
    <form class="for form-control form-row" method="post">
      {% csrf_token %}
      <div class="card-body">
        <div class="alert alert-danger">
          <strong>Cuidado!</strong>
          <br>
          Estas seguro de eliminar la Habitación {{ object.id }}.
          <br>
          <p><strong>Descripción:</strong> {{ object.description}} <strong>y Precio:</strong> {{ object.price }}<strong> y ventilacion:</strong> {{ object.get_ventilacion_display }}<strong> y Temperatura del Agua:</strong> {{ object.get_temperaturaAgua_display }}</p>
        </div>
      </div>
      <div class="card-footer text-center">
        <input type="submit" class="btn btn-warning" value="Eliminar">
        <a href="{% url 'listarReservaciones' %}" class="btn btn-danger">Cancelar</a>
      </div>
    </form>
  </div>
</div>
<br>
<br>
<br>
<br>
<br>

{% endblock %}

sghu/administration/templates/manageReservation.html
{%extends 'base.html'%}
{% load static %}
{%block title%} GestionarReservación {% endblock %}



{% block content %}
{% if request.user.is_staff %}
    <div class="container">
    <div class="bg-white">
        <br>
        <br>
        <div class="row bg-white justify-content-center">
            <div class="col-sm-12 col-md-6 col-lg-8 col-xl-11">
                <br>
                <h1 class="text-center">Reservaciones</h1>
                <div class="table-responsive py-2">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Edad</th>
                            <th>Pago:</th>
                            <th>Fecha Inicio</th>
                            <th>Fecha Fin</th>
                            <th>Habitación</th>
                            <th colspan="2">Opciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if reservations %}
                            {% for e in reservations %}
                                
                                    <tr>
                                        <td>{{ e.name }}</td>
                                        <td>{{ e.edad }}</td>
                                        <td>{{ e.get_metodoDePago_display }}</td>
                                        <td>{{ e.fechaDeInicio }}</td>
                                        <td>{{ e.fechaDeFin }}</td>
                                        <td>
                                           
                                            <div class="row">
                                                <div class="col-md-4">
                                                   {% for room in rooms %}
                                                        {% if room.id == e.idRoom.id %}
                                                         {% if room.price < 600 %}
                                                             <img src="{% static 'medias/Habitaciones/1.jpg' %}" class="h-200 w-100" >
                                                         {% elif room.price < 800 and room.price >= 600 %}
                                                             <img src="{% static 'medias/Habitaciones/2.jpg' %}" class="img-fluid">
                                                         {% elif room.price < 900 and room.price >= 800 %}
                                                                <img src="{% static 'medias/Habitaciones/3.jpg' %}" class="img-fluid">
                                                         {% elif room.price <= 1000 and room.price >= 900 %}
                                                             <img src="{% static 'medias/Habitaciones/4.jpg' %}" class="img-fluid">
                                                        
                                                        {% endif %}
                                                                     
                                                                     
                                                </div>
                                                <div class="col-md-8">
                                                    <p>{{ room.description }}</p>
                                                    <p><strong>Precio:</strong> {{ room.price }} CUP</p>
                                                </div>
                                            </div> 
                                             {% endif %}
                                            {% endfor %}
                                        </td>
                                        <td><a href="{% url 'modificarReservaciones' e.id %}" class="btn"><img src="{% static 'medias/modificar.png'%}" alt="" style="width: 40px;"></a> </td>
                                        <td><a href="{% url 'EliminarReservacionbyAdmin' e.id %}" class="btn" ><img src="{% static 'medias/eliminar.png'%}" alt="" style="width: 40px;"></a> </td>
                                    </tr>
                                
                            {% endfor %}
                       
                        </tbody>
                    </table>
                </div>
                        {% else %}
                            <tr>
                                <td>No hay datos a mostrar</td>
                            </tr>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{%else%}
<h1 class="text-center ">Acceso Denegado</h1>
{% endif %}
<br>
<br>
<br>
<br>
<br>

{%endblock%}

sghu/administration/templates/manageroom.html
{%extends 'base.html'%}
{% load static %}
{%block title%} Habitaciones {% endblock %}



{% block content %}
{% if request.user.is_staff %}
    <div class="container">
    <div class="bg-white">
        <br>
        <br>
        <div class="row bg-white justify-content-center">
            <div class="col-sm-12 col-md-6 col-lg-8 col-xl-8">
                <br>
                <h1 class="text-center">Habitaciones</h1>
                <div class="card-footer">
                    {% if not todasHabitaciones  %}
                    <a  class="btn btn-primary" href="{% url 'anadirRoom' %}">Añadir Habitación</a>
                    {% else %}
                    <a  class="btn btn-primary" disabled href="{% url 'anadirRoom' %}">Todas las habitaciones están creadas</a>
                    {% endif %}
                </div>
                <div class="table-responsive py-2">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Descripcion</th>
                            <th>Precio</th>
                            <th>Ventilación</th>
                            <th>Temperatura de agua</th>
                            <th>Televisión</th>
                            <th colspan="2">Opciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if object_list %}
                            {% for e in object_list %}
                                
                                    <tr>
                                        <td>{{ e.description }}</td>
                                        <td>{{e.price}}</td>
                                        <td>{{e.get_ventilacion_display}}</td>
                                        <td>{{e.get_temperaturaAgua_display}}</td>
                                        <td>{{e.television}}</td>
                                        <td><a href="{% url 'modRoom' e.id %}" class="btn"><img src="{% static 'medias/modificar.png'%}" alt="" style="width: 40px;"></a> </td>
                                        <td><a href="{% url 'eliminarRoom' e.id %}" class="btn" ><img src="{% static 'medias/eliminar.png'%}" alt="" style="width: 40px;"></a> </td>
                                    </tr> 
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td>No hay datos a mostrar</td>
                            </tr>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{%else%}
     <h1 class="text-center ">Acceso Denegado</h1>
{% endif %}
<br>
<br>
<br>
<br>
<br>
{%endblock%}

sghu/administration/templates/modRoom.html
{%extends 'base.html'%}
{% load static %}
{% load crispy_forms_tags %}
{%block title%} Update Room {% endblock %}


{% block content %}
<style>
    body{
        background-image: url("{% static 'medias/esteSi.jpg'%}");
        background-size: 100% 100%;
    
    }
    </style>

    <div class="">
        <br>
        <br>
        {% block titulo %}
            <h3 class="card-title text-center fw-bold">Actualizar Room</h3>
        {% endblock %}

        <div class="container w-50">

            <form class="for form-control form-row" method="post">

                <div class="card-body">
                    {% csrf_token %}
                    {% block forms %}
                        {{ form| crispy }}
                    {% endblock %}


                </div>
                <div class="card-footer">
                    {% block buttons %}
                        <input type="submit" class="btn btn-primary" style="margin-left: 100px;" value="Actualizar">
                    {% endblock %}


                    <a href="{% url 'listarRoom' %}" class="btn btn-danger" style="margin-left: 200px;">Cancelar</a>

                </div>
            </form>


        </div>
        <br>
        <br>
        <br>
    </div>
{% endblock %}

sghu/administration/templates/users_list.html
{% extends 'base.html' %}
{% load static %}
{%block title%} Manage Users {% endblock %}
{% block content %}

 {% if request.user.is_superuser %}
<style>
    table {
      border-collapse: collapse;
      width: 100%;
      margin-bottom: 1em;
    }
    th, td {
      text-align: left;
      padding: 0.5em;
      border-bottom: 1px solid #ddd;
    }
    th {
      background-color: #f2f2f2;
      font-weight: bold;
    }
    td.actions {
      white-space: nowrap;
    }
    td.actions form, td.actions a {
      display: inline-block;
      margin-right: 0.5em;
    
    }
    
  </style>
  <div class="bg-light">
  <table>
    <thead>
      <tr>
        <th>Nombre de usuario</th>
        <th>Correo electrónico</th>
        <th>Nombre</th>
        <th>Apellidos</th>
        <th>Fecha de registro</th>
        <th>Activo</th>
        <th>Staff</th>
        <th>SuperUsuario</th>
        <th>&nbsp&nbsp&nbsp&nbsp&nbspAcciones</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        {% if not request.user.username == user.username%}
        <tr>
          <td>&nbsp&nbsp{{ user.username }}</td>
          <td>&nbsp{{ user.email }}</td>
          <td>{{ user.first_name }}</td>
          <td>{{ user.last_name }}</td>
          <td>{{ user.date_joined }}</td>
          <td>{% if user.is_active %}Si
            {% else %}NO
            {% endif %}
          </td>
          <td>
            {% if user.is_staff %}Si
            {% else %}No
            {% endif %}</td>
            <td>
              {% if user.is_superuser%}Si
              {% else %}No
              {% endif %}</td>
          <td class="actions">
            <button  class=" btn" onclick="window.location.href='{% url 'editarUsuario' user.id %}'" ><img src="{% static 'medias/modificar.png'%}" alt="" style="width: 40px;"></button>
            <form method="post" action="{% url 'eliminar_usuario' user.username %}">
                {% csrf_token %}
                <button  class=" btn"type="submit"><img src="{% static 'medias/eliminar.png'%}" alt="" style="width: 40px;"></button>
            </form>
          </td>
        </tr>
         {%endif%}
      {% endfor %}
    </tbody>
  </table>
</div>
     {%else%}
     <h1 class="text-center ">Acceso Denegado</h1>
    {% endif %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

{% endblock %}